### ISSUE TITLE
handleDelete not working

### ISSUE THREAD

**Issue by tsypaul** [tsypaul/EmailApp#1]
In Mails.js, handleDelete(id) function is supposed to delete an item in the state emails, instead it deletes all the items in the list

**Comment by michaelqiji** [comment]
I didn't see any problem in handleDelete(id), does the handleSearch works?

**Comment by tsypaul** [comment]
When you run your code, does it delete the whole list or just one item? @michaelqiji

**Comment by michaelqiji** [comment]
@tsypaul How did you start your app? You can write it down in readme file. Is there a backend as well?

**Comment by tsypaul** [comment]
@michaelqiji Added a readme. There is no backend. I hardcoded the data in the component.

**Comment by tsypaul** [comment]
And handleSearch does not work
